# Generated by Django 4.1.13 on 2024-04-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название одежды')),
                ('image', models.CharField(max_length=500, verbose_name='Ссылка на фото')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
